version: '3.1'

services:
  mongo:
    image: mongo:4.4-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${EVENT_STORAGE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${EVENT_STORAGE_PASSWORD}
    env_file:
      - .env

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${EVENT_STORAGE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${EVENT_STORAGE_PASSWORD}
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: always
    networks:
      - rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbirmq-log:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${EVENT_BUS_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${EVENT_BUS_PASSWORD}
    env_file:
      - .env

volumes:
  mongo-data:
    driver: local
  rabbitmq-data:
    driver: local
  rabbirmq-log:
    driver: local

networks:
  rabbitmq:
    driver: bridge
