version: '3.1'

services:
  postgresql:
    image: postgres:latest
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${EVENT_STORAGE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${EVENT_STORAGE_PASSWORD}
    env_file:
      - .env

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${EVENT_STORAGE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${EVENT_STORAGE_PASSWORD}
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    networks:
      - rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbirmq-log:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${EVENT_BUS_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${EVENT_BUS_PASSWORD}
    env_file:
      - .env

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgresql-data:
    driver: local
  mongo-data:
    driver: local
  rabbitmq-data:
    driver: local
  rabbirmq-log:
    driver: local

networks:
  postgresql:
    driver: bridge
  rabbitmq:
    driver: bridge
